[project]
name = "cork"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "gunicorn>=26.2.0",
    "helios",
    "ruff>=0.16.6",
]

[project.scripts]
serve = "app:main"

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv]
package = true

[tool.uv.build-backend]
module-name = "app"
module-root = ""

[tool.uv.sources]
helios = { path = "../helios", editable = true }
luna = { path = "../luna", editable = true }

[tool.ruff]
target-version = "py314"

[tool.ruff.format]
indent-style = "tab"
nested-string-quote-style = "preferred"
quote-style = "double"

[tool.ruff.lint]
ignore = [
	"RUF012",
]

[tool.ruff.lint.isort]
case-sensitive = true
known-first-party = ["app"]
force-sort-within-sections = true
order-by-type = false

[dependency-groups]
dev = [
    "luna",
]
