[Service]
ExecStart=
ExecStart=/opt/cork/venv/bin/gunicorn \
	--workers 2 \
	--reload \
	--access-logfile - \
	--error-logfile - \
	app.main:app
PrivateTmp=no
ProtectSystem=no
ProtectHome=no
ReadWritePaths=
